# OpenAI Integration Docker Compose
# Use this configuration when you want to use OpenAI embeddings instead of local Ollama

version: '3.8'

services:
  8fs:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=info
      # Authentication configuration
      - DEFAULT_ACCESS_KEY=${DEFAULT_ACCESS_KEY:-AKIAIOSFODNN7EXAMPLE}
      - DEFAULT_SECRET_KEY=${DEFAULT_SECRET_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
      # Server configuration
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      # Storage configuration
      - STORAGE_DRIVER=filesystem
      - STORAGE_BASE_PATH=/app/data
      # AI Integration (OpenAI)
      - AI_ENABLED=true
      - AI_PROVIDER=openai
      - AI_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID:-}
      - OPENAI_EMBED_MODEL=${OPENAI_EMBED_MODEL:-text-embedding-3-small}
      - AI_TIMEOUT=30s
      - AI_CHUNK_SIZE=500
      - AI_MAX_RETRIES=3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - s3-network

  # Optional: Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - s3-network
    profiles: ["monitoring"]

networks:
  s3-network:
    driver: bridge